### ISSUE TITLE
Я писал, что нужно метод, а не эта функция

### ISSUE THREAD

**Issue by AlexandrShcherbakov** [Andareon/RayTracing#33]
https://github.com/Andareon/RayTracing/blob/fe51226eb6d7c7cfb08950c736cc74ed4be05470/main.cpp#L113
Внутри класса Ray пиши:
void multiplyColor(const vec3 &c) {this->color *- c;}
Что-то такое должно быть.

**Comment by Andareon** [comment]
С добавлением функции reflect, есть ли в этом смысл?

**Comment by AlexandrShcherbakov** [comment]
Какая ещё функция reflect? Я ничего не понял.
