### ISSUE TITLE
Перепиши на обычный for

### ISSUE THREAD

**Issue by AlexandrShcherbakov** [Andareon/RayTracing#35]
https://github.com/Andareon/RayTracing/blob/fe51226eb6d7c7cfb08950c736cc74ed4be05470/main.cpp#L232
Здесь for-each явно не нужен.
И ниже тоже.

**Comment by Andareon** [comment]
Можешь пояснить?

**Comment by AlexandrShcherbakov** [comment]
Тут github не ту строку приделал. Исправлю.
